name: codequality.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-sonarcloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back
    name: SonarCloud Backend Code Analysis Scan
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set Up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: "zulu"
      - name: Cache SonarCloud Packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven Packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Backend Dependencies and Build Spring Boot Application
        run: mvn clean package -DskipTests
      - name: Execute Backend Tests
        run: mvn test
      - name: Generate JaCoCo Code Coverage Report
        run: mvn jacoco:report
      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco
      - name: Print SonarCloud Token
        run: echo $SONAR_TOKEN
      - name: Ping SonarCloud Server
        run: ping -c 4 sonarcloud.io
      - name: Build and Analyze Backend Code
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=com.openclassrooms.bobapp -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}

  frontend-sonarcloud:
    defaults:
      run:
        working-directory: ${{ github.workspace }}/front
    strategy:
      matrix:
        node-version: [ 14.15.0, 16.10.0 ]
    name: SonarCloud Frontend Code Analysis Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Execute Frontend Tests and Generate Code Coverage Report
        run: npm run test:prod
      - name: Build Frontend Code
        run: npm run build:prod --base-href="./"
      - name: Upload Coverage Reports Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report ${{ matrix.node-version }}
          path: front/coverage/bobapp
      - name: Print SonarCloud Token
        run: echo $SONAR_TOKEN
      - name: Ping SonarCloud Server
        run: ping -c 4 sonarcloud.io
      - name: Analyze Frontend Code
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=taylorfullstack_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-frontend
            -Dsonar.organization=taylorfullstack
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info