name: Frontend CI

on:
  push:
    paths:
      - 'front/**'
      - '.github/workflows/**'
    branches:
      - main

  pull_request:
    paths:
      - 'front/**'
      - '.github/workflows/**'
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests and Generate Code Coverage Report
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_build_and_push:
    needs: test_and_coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest