name: tests.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/back
    strategy:
      matrix:
        java-version: [ 11 ]
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4
      - name: Set Up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"
      - name: Install Backend Dependencies
        run: mvn clean install
      - name: Execute Backend Tests
        run: mvn clean test
      - name: Generate JaCoCo Code Coverage Report
        run: mvn jacoco:report
      - name: Upload JaCoCo Code Coverage Report to GitHub
        uses: actions/upload-artifact@v4.3.3
        with:
          name: JaCoCo Code Coverage Report
          path: ./back/target/site/jacoco/
